### PR TITLE
Fix: Add button

### PR DESCRIPTION
**Pull request by JosefBud**
In order to better fit the vision of what this page should be, product decided to add a button

Resolves issue #1

### CODE REVIEW

**Review by FabledWeb — APPROVED** [review]
Flawless execution. Though I'm not sure why product wanted this to be a regular button instead of a submit button. 🤷

**Review by PercipioDelightend — APPROVED** [review]
Great work @JosefBud

**Review by amanda-hussey-percipio — APPROVED** [review]
👌 sheer perfection

**Comment by terrancemacgregor** [comment]
Approving.  Excellent work.

**Pull request merged**
